- name: play level variables
  hosts: local
  connection: local
  vars:
   Person : Siva # equal to name=Siva in shell
  tasks:
   - name: print hello world
     ansible.builtin.debug:
     #variable must be surrounded in double quotes
      msg: "my name is {{Person}}"