- name: variables from files
  hosts: local
  connection: local
  vars_files:
   - course.yaml
  tasks:
  ansible.builtin.debug:
   msg: "Hello Iam learning {{COURSE}} with duration {{DURATION}} and trainer is {{TRAINER}}"