- name: Installing packages
  hosts: frontend
  become: yes
  tasks:
   - name: Installing nginx,mysql,zip
     ansible.builtin.package:
      name: "{{item}}"
      state: present
     loop:
     - nginx
     - mysql
     - zip
