- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ramesh, Suresh, Rajesh, Rahul"
  tasks:
   - name: print name
     ansible.builtin.debug:
      msg: "Hello , {{person | default('Ramesh')}}"

   - name: print names
     ansible.builtin.debug:
      msg: "Hello , {{persons | split(',')}}"

   - name: print names
     ansible.builtin.debug:
      msg: "Hello , {{persons | split(',')}}"

   - name: convert map into list
     vars:
      course:
       name: ansible
       duration: 120HR
       trainer: Sivakumar
     ansible.builtin.debug:
      msg: "Hello , {{course | dict2items}}"
    
   - name: convert list into map
     vars:
      course:
       - {'key': 'name', 'value': 'ansible'}
       - {'key': 'duration', 'value': '120HR'}
       - {'key': 'trainer', 'value': 'Sivakumar'}
     ansible.builtin.debug:
      msg: "Hello , {{course | items2dict }}"

   - name: convert name into uppercase
     vars:
      person: sivakumar
     ansible.builtin.debug:
      msg: "Hello , {{person | upper}}"

   - name: convert name into lowercase
     vars:
      person: SIVAKUMAR
     ansible.builtin.debug:
      msg: "Hello , {{person | lower}}"

   - name: check ip address is valid or not
     vars:
      ipaddress: 192.168.0.1
     ansible.builtin.debug:
      msg: "{{ipaddress | ansible.utils.ipaddr}}"
