- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: redirect ls output to file
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_result

  - name: print the outcome
    ansible.builtin.debug: 
     msg: "{{command_result}}"

  - name: redirect ls output to file using command
    ansible.builtin.command: "ls -ltr"
    register: command_output

  - name: print the output
    ansible.builtin.debug: 
     msg: "{{command_output}}"
     