- name: user creation
  hosts: local
  connection: local
  tasks:
  - name: check chitti user exists or not
    ansible.builtin.command: id chitti
    register: output
    ignore_errors: true

  - name: print the outcome
    ansible.builtin.debug: 
     msg: "{{ output }}"

  - name: create user
    become: yes
    ansible.builtin.command: useradd chitti
    when: output.rc!=0

  - name: user already exists
    ansible.builtin.debug:
     msg: "user already exist"
    when: output.rc == 0
